apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-app
        image: cybagetest/ekstest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
